name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm tsc