name: Bump Package Version
on:
  pull_request:
    types: [push]
    branches: [dev]

jobs:
  bump_package_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Retrieve Update Type
        shell: bash {0}
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: