name: Bump Version Type
on: pull_request
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Update Type
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          read val < <(echo "$BODY" | grep -E '^change: major|minor|patch$')
          echo "${val:8:13}"