name: Validate PR Schema
on:
  pull_request:
    types: [opened,edited,reopened]
    branches: [dev]

jobs:
  validate_pr_schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retrieve and Validate Update Type
        shell: bash
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "$BODY"
          echo "val=$(echo "$BODY" | grep -E '^change: (major|minor|patch)$')" >> $GITHUB_ENV
          echo "val: ${{ env.val }}"
          if [ -z "$val" ]; then exit 1; fi

